### ISSUE TITLE
version commit pattern

### ISSUE THREAD

**Issue by mbjelac** [infobip/jira-version-generator#2]
Some projects cannot satisfy the precondition "Project artifactId matches the name of the repository.". This can be eliminated by providing an optional setting of version commit pattern.
Also with this change the jira version generator would be decoupled from Maven release plugin.

The idea is to provide a setting for the plugin in which the plugin user would define a regex pattern for extracting the version from a commit message. The regex pattern must specify 1st capturing group for extracting the version.

For example, the following input pattern:
`\[maven-release-plugin\] prepare release infobip-ussd-appcore-parent-(.*)`

and the following commit message:
`[maven-release-plugin] prepare release infobip-ussd-appcore-parent-2.22.0`

would generate version 
`2.22.0`

**Comment by lpandzic** [comment]
Fixed.
